ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toclevels: 5
= Debezium installation
:toc:
:toc-placement: macro
:sectanchors:
:linkattrs:
:bl: pass:[ +]
:debezium-version: 0.9.2
:debezium-version-full: {debezium-version}.Final

toc::[]


== 1. Overview

There are primarily two ways of setting up the kafka connect environment and installing the Debezium connectors, either the manually installation or using the Debezium Docker images. At this document, the manual installation procedure is described.

Installation environment requirements:

* https://www.postgresql.org/docs/9.6/static/index.html[PostgreSQL] (v9.6.10)
* https://github.com/eulerto/wal2json[wal2json]
* https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/0.9.2.Final/debezium-connector-postgres-{debezium-version-full}-plugin.tar.gz[Postgres Debezium connector] (v0.9.2)
* https://archive.apache.org/dist/kafka/2.1.1/kafka_2.12-2.1.1.tgz[Kafka] (v2.12-2.1.1) or https://docs.confluent.io/current/installation/installing_cp/zip-tar.html[Confluent platform] (community v5.1.2-2.11)
* CentOS Linux 7 (kernel: Linux 3.10.0-862.11.6.el7.x86_64)

[NOTE]
====
Note that Java 8 or later is required to run the Debezium connectors.
====

The installation procedure is performed in two parts:

* The link:#logical-decoding-plugin-inst[Logical decoding plugin] installation, where the installation of the https://github.com/eulerto/wal2json[wal2json] logical decoding output plugin at the postgresql database is performed.
* The link:#kafka-confluent-inst[Debezium connector installation], where the Kafka connect environment setup and the Debezium connector installation are included.


[[logical-decoding-plugin-inst]]
== 2. Installing Logical Decoding plugin
Logical decoding is the process of extracting all persistent changes to a database's tables into a coherent, easy to understand format which can be interpreted without detailed knowledge of the database's internal state.

As of PostgreSQL 9.4, logical decoding is implemented by decoding the contents of the write-ahead log, which describe changes on a storage level, into an application-specific form such as a stream of tuples or SQL statements. In the context of logical replication, a slot represents a stream of changes that can be replayed to a client in the order they were made on the origin server. Each slot streams a sequence of changes from a single database. The output plugins transform the data from the write-ahead log's internal representation into the format the consumer of a replication slot desires. Plugins are written in C, compiled, and installed on the machine which runs the PostgreSQL server, and they use a number of PostgreSQL specific APIs, as described by the https://www.postgresql.org/docs/9.6/static/logicaldecoding-output-plugin.html[PostgreSQL documentation].

Debezium’s PostgreSQL connector works with one of Debezium’s supported logical decoding plugin, https://github.com/debezium/postgres-decoderbufs/blob/master/README.md[protobuf] or https://github.com/eulerto/wal2json/blob/master/README.md[wal2json], to encode the changes in either https://github.com/google/protobuf[Protobuf] format or http://www.json.org/[JSON] format respectively.

[WARNING]
====
The Debezium logical decoding plugins have only been installed and tested on _Linux_ machines. For Windows and other OSes it may require different installation steps
====

[WARNING]
====
*wal2json limitations*

* wal2json plug-in is not able to process qouted identifiers (https://github.com/eulerto/wal2json/issues/35[issue])
* wal2json plug-in does not emit events for tables without primary keys
* wal2json plug-in does not support special values (`NaN` or `infinity`) for floating point types
====

[NOTE]
====
*More information* about the logical decoding and output plugins can be found at:

* https://www.postgresql.org/docs/9.6/static/logicaldecoding-explanation.html[PostgreSQL logical decoding explanation]
* https://www.postgresql.org/docs/9.6/static/logicaldecoding-output-plugin.html[PostgreSQL logical decoding output plugin]
* https://wiki.postgresql.org/wiki/Logical_Decoding_Plugins[PostgreSQL logical decoding plugins]
====

[[logical-decoding-output-plugin-installation]]
=== 2.1 Installation
At the current installation example, the https://github.com/eulerto/wal2json[wal2json] output plugin for logical decoding is used. The wal2json output plugin produces a JSON object per transaction. All of the new/old tuples are available in the JSON object. The plugin *compilation and installation* is performed by executing the related commands extracted from the https://github.com/debezium/docker-images/blob/master/postgres/9.6/Dockerfile[Debezium docker image file].

Before executing the commands, make sure that the user has the privileges to write the `wal2json` library at the PostgreSQL `_lib_` directory (at the test environment, the directory is: `/usr/pgsql-9.6/lib/`). Also note that the installation process requires the PostgreSQL utility https://www.postgresql.org/docs/9.6/static/app-pgconfig.html[pg_config]. Verify that the `PATH` environment variable is set so as the utility can be found. If not, update the `PATH` environment variable appropriately. For example at the test environment:
[source,bash]
----
export PATH="$PATH:/usr/pgsql-9.6/bin"
----

.*wal2json* installation commands
[source,bash]
----
$ git clone https://github.com/eulerto/wal2json -b master --single-branch \
&& cd wal2json \
&& git checkout d2b7fef021c46e0d429f2c1768de361069e58696 \
&& make && make install \
&& cd .. \
&& rm -rf wal2json
----
